id: I4EE279B3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T23:36:56+00:00'
last_modified: '2022-06-08T12:48:36.586598+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30441
  title: དབུ་མའི་ཟབ་གནད་སྙིང་པོར་དྲིལ་བའི་ལེགས་བཤད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AC44:
      image_group_id: I1PD30297
      title: Volume 1 of dbu ma'i zab gnad snying por dril ba'i legs bshad
      total_pages: 178
      order: 1
      base_file: AC44.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
