id: P006946
initial_creation_type: ocr
source_metadata:
  id: bdr:W30441
  title: དབུ་མའི་ཟབ་གནད་སྙིང་པོར་དྲིལ་བའི་ལེགས་བཤད
  author: ''
  volumes:
    ecb194bc19014824b2d8ccea6c74984d:
      image_group_id: I1PD30297
      title: ''
      volume_number: 1
      total_pages: 178
ebook_metadata:
  title: དབུ་མའི་ཟབ་གནད་སྙིང་པོར་དྲིལ་བའི་ལེགས་བཤད
  author: ''
  sku: P006946
  cover: cover.jpg
  layers:
  - pagination
