id: P006946
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:32:14.765686
source_metadata:
  id: bdr:W30441
  title: དབུ་མའི་ཟབ་གནད་སྙིང་པོར་དྲིལ་བའི་ལེགས་བཤད
  author: ''
  volumes:
    8a2d52cc00e34eb985a2fc851ec418c5:
      image_group_id: I1PD30297
      title: Volume 1 of dbu ma'i zab gnad snying por dril ba'i legs bshad
      volume_number: 1
      total_pages: 178
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
